//go:build !exclude_generated
// +build !exclude_generated

// Code generated by storm orm generate-orm; DO NOT EDIT.
//
// This file was automatically generated from Go struct definitions.
// Any changes made to this file will be lost when regenerating.
//
// Source package: todo
// Models found: 7
// Generated on: 2025-07-17 00:36:07 CEST
//
// To regenerate this file, run:
//   storm orm generate-orm --package=todo
//
// For more information, see:
//   https://github.com/eleven-am/storm

package todo

import (
	"github.com/eleven-am/storm/internal/orm"
	"time"
)

// Categorys provides type-safe column references for Category
var Categorys = struct {
	ID orm.StringColumn `json:"id"`

	UserID orm.StringColumn `json:"user_id"`

	Name orm.StringColumn `json:"name"`

	Color orm.StringColumn `json:"color"`

	Description orm.StringColumn `json:"description"`

	CreatedAt orm.TimeColumn `json:"created_at"`

	UpdatedAt orm.TimeColumn `json:"updated_at"`
}{

	ID: orm.StringColumn{Column: orm.Column[string]{Name: "id", Table: "categories"}},

	UserID: orm.StringColumn{Column: orm.Column[string]{Name: "user_id", Table: "categories"}},

	Name: orm.StringColumn{Column: orm.Column[string]{Name: "name", Table: "categories"}},

	Color: orm.StringColumn{Column: orm.Column[string]{Name: "color", Table: "categories"}},

	Description: orm.StringColumn{Column: orm.Column[string]{Name: "description", Table: "categories"}},

	CreatedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "created_at", Table: "categories"}}},

	UpdatedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "updated_at", Table: "categories"}}},
}

// CategoryTable provides table-level operations for Category
var CategoryTable = orm.Table{
	Name:        "categories",
	PrimaryKeys: []string{"id"},
}

// Comments provides type-safe column references for Comment
var Comments = struct {
	ID orm.StringColumn `json:"id"`

	TodoID orm.StringColumn `json:"todo_id"`

	UserID orm.StringColumn `json:"user_id"`

	Content orm.StringColumn `json:"content"`

	CreatedAt orm.TimeColumn `json:"created_at"`

	UpdatedAt orm.TimeColumn `json:"updated_at"`
}{

	ID: orm.StringColumn{Column: orm.Column[string]{Name: "id", Table: "comments"}},

	TodoID: orm.StringColumn{Column: orm.Column[string]{Name: "todo_id", Table: "comments"}},

	UserID: orm.StringColumn{Column: orm.Column[string]{Name: "user_id", Table: "comments"}},

	Content: orm.StringColumn{Column: orm.Column[string]{Name: "content", Table: "comments"}},

	CreatedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "created_at", Table: "comments"}}},

	UpdatedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "updated_at", Table: "comments"}}},
}

// CommentTable provides table-level operations for Comment
var CommentTable = orm.Table{
	Name:        "comments",
	PrimaryKeys: []string{"id"},
}

// Tags provides type-safe column references for Tag
var Tags = struct {
	ID orm.StringColumn `json:"id"`

	Name orm.StringColumn `json:"name"`

	Color orm.StringColumn `json:"color"`

	CreatedAt orm.TimeColumn `json:"created_at"`
}{

	ID: orm.StringColumn{Column: orm.Column[string]{Name: "id", Table: "tags"}},

	Name: orm.StringColumn{Column: orm.Column[string]{Name: "name", Table: "tags"}},

	Color: orm.StringColumn{Column: orm.Column[string]{Name: "color", Table: "tags"}},

	CreatedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "created_at", Table: "tags"}}},
}

// TagTable provides table-level operations for Tag
var TagTable = orm.Table{
	Name:        "tags",
	PrimaryKeys: []string{"id"},
}

// Todos provides type-safe column references for Todo
var Todos = struct {
	ID orm.StringColumn `json:"id"`

	UserID orm.StringColumn `json:"user_id"`

	CategoryID orm.StringColumn `json:"category_id"`

	Title orm.StringColumn `json:"title"`

	Description orm.StringColumn `json:"description"`

	Status orm.Column[interface{}] `json:"status"`

	Priority orm.Column[interface{}] `json:"priority"`

	DueDate orm.TimeColumn `json:"due_date"`

	CompletedAt orm.TimeColumn `json:"completed_at"`

	CreatedAt orm.TimeColumn `json:"created_at"`

	UpdatedAt orm.TimeColumn `json:"updated_at"`
}{

	ID: orm.StringColumn{Column: orm.Column[string]{Name: "id", Table: "todos"}},

	UserID: orm.StringColumn{Column: orm.Column[string]{Name: "user_id", Table: "todos"}},

	CategoryID: orm.StringColumn{Column: orm.Column[string]{Name: "category_id", Table: "todos"}},

	Title: orm.StringColumn{Column: orm.Column[string]{Name: "title", Table: "todos"}},

	Description: orm.StringColumn{Column: orm.Column[string]{Name: "description", Table: "todos"}},

	Status: orm.Column[interface{}]{Name: "status", Table: "todos"},

	Priority: orm.Column[interface{}]{Name: "priority", Table: "todos"},

	DueDate: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "due_date", Table: "todos"}}},

	CompletedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "completed_at", Table: "todos"}}},

	CreatedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "created_at", Table: "todos"}}},

	UpdatedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "updated_at", Table: "todos"}}},
}

// TodoTable provides table-level operations for Todo
var TodoTable = orm.Table{
	Name:        "todos",
	PrimaryKeys: []string{"id"},
}

// TodoTags provides type-safe column references for TodoTag
var TodoTags = struct {
	TodoID orm.StringColumn `json:"todo_id"`

	TagID orm.StringColumn `json:"tag_id"`

	CreatedAt orm.TimeColumn `json:"created_at"`
}{

	TodoID: orm.StringColumn{Column: orm.Column[string]{Name: "todo_id", Table: "todo_tags"}},

	TagID: orm.StringColumn{Column: orm.Column[string]{Name: "tag_id", Table: "todo_tags"}},

	CreatedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "created_at", Table: "todo_tags"}}},
}

// TodoTagTable provides table-level operations for TodoTag
var TodoTagTable = orm.Table{
	Name:        "todo_tags",
	PrimaryKeys: []string{"todo_id", "tag_id"},
}

// Users provides type-safe column references for User
var Users = struct {
	ID orm.StringColumn `json:"id"`

	Email orm.StringColumn `json:"email"`

	Name orm.StringColumn `json:"name"`

	Password orm.StringColumn `json:"password_hash"`

	IsActive orm.BoolColumn `json:"is_active"`

	CreatedAt orm.TimeColumn `json:"created_at"`

	UpdatedAt orm.TimeColumn `json:"updated_at"`
}{

	ID: orm.StringColumn{Column: orm.Column[string]{Name: "id", Table: "users"}},

	Email: orm.StringColumn{Column: orm.Column[string]{Name: "email", Table: "users"}},

	Name: orm.StringColumn{Column: orm.Column[string]{Name: "name", Table: "users"}},

	Password: orm.StringColumn{Column: orm.Column[string]{Name: "password_hash", Table: "users"}},

	IsActive: orm.BoolColumn{Column: orm.Column[bool]{Name: "is_active", Table: "users"}},

	CreatedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "created_at", Table: "users"}}},

	UpdatedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "updated_at", Table: "users"}}},
}

// UserTable provides table-level operations for User
var UserTable = orm.Table{
	Name:        "users",
	PrimaryKeys: []string{"id"},
}

// UserTags provides type-safe column references for UserTag
var UserTags = struct {
	UserID orm.StringColumn `json:"user_id"`

	TagID orm.StringColumn `json:"tag_id"`

	CreatedAt orm.TimeColumn `json:"created_at"`
}{

	UserID: orm.StringColumn{Column: orm.Column[string]{Name: "user_id", Table: "user_tags"}},

	TagID: orm.StringColumn{Column: orm.Column[string]{Name: "tag_id", Table: "user_tags"}},

	CreatedAt: orm.TimeColumn{ComparableColumn: orm.ComparableColumn[time.Time]{Column: orm.Column[time.Time]{Name: "created_at", Table: "user_tags"}}},
}

// UserTagTable provides table-level operations for UserTag
var UserTagTable = orm.Table{
	Name:        "user_tags",
	PrimaryKeys: []string{"user_id", "tag_id"},
}
