//go:build !exclude_generated
// +build !exclude_generated

// Code generated by storm orm generate-orm; DO NOT EDIT.
//
// This file was automatically generated from Go struct definitions.
// Any changes made to this file will be lost when regenerating.
//
// Source package: todo
// Model: TodoTag
// Generated on: 2025-07-17 01:02:48 CEST
//
// To regenerate this file, run:
//   storm orm generate-orm --package=todo
//
// For more information, see:
//   https://github.com/eleven-am/storm

package todo

import (
	"context"
	"fmt"
	"github.com/eleven-am/storm/internal/orm"
	"github.com/jmoiron/sqlx"
)

// TodoTagRepository provides type-safe operations for TodoTag
//
// The repository inherits these operations from orm.Repository:
//
// Single Record Operations:
//   - Create(ctx, record) - Insert single record
//   - FindByID(ctx, id) - Find record by primary key
//   - Update(ctx, record) - Update single record by primary key
//   - Delete(ctx, id) - Delete record by primary key ID
//   - DeleteRecord(ctx, record) - Delete record using the record instance
//
// Batch Operations:
//   - CreateMany(ctx, records) - Insert multiple records in transaction
//   - UpdateMany(ctx, updates, condition) - Update multiple records with condition
//   - BulkUpdate(ctx, records, opts) - Bulk update using CTE with VALUES
//   - Upsert(ctx, record, opts) - Insert or update on conflict
//   - UpsertMany(ctx, records, opts) - Batch upsert operations
//
// Query Building:
//   - Query() - Create new query builder for complex queries
//   - QueryContext(ctx) - Create query builder with context support
//
// Example usage:
//
//	// Single operations
//	todotag, err := repo.FindByID(ctx, "123")
//	err = repo.Create(ctx, &newTodoTag)
//
//	// Batch operations
//	err = repo.CreateMany(ctx, multipleTodoTags)
//	rowsAffected, err := repo.UpdateMany(ctx, updates, condition)
//
//	// Complex queries
//	results, err := repo.Query().Where(condition).OrderBy("created_at DESC").Find()
type TodoTagRepository struct {
	*orm.Repository[TodoTag]
}

func newTodoTagRepository(db *sqlx.DB) (*TodoTagRepository, error) {
	baseRepo, err := orm.NewRepository[TodoTag](db, TodoTagMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository: %w", err)
	}

	return &TodoTagRepository{
		Repository: baseRepo,
	}, nil
}

func newTodoTagRepositoryWithTx(tx *sqlx.Tx) (*TodoTagRepository, error) {
	baseRepo, err := orm.NewRepositoryWithTx[TodoTag](tx, TodoTagMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository with transaction: %w", err)
	}

	return &TodoTagRepository{
		Repository: baseRepo,
	}, nil
}

// Query returns a type-safe query builder for TodoTag
//
// Example:
//
//	allTodoTags, err := repo.Query().
//	    OrderBy(TodoTags.TodoID.Desc()).
func (r *TodoTagRepository) Query() *TodoTagQuery {
	return &TodoTagQuery{
		Query: r.Repository.Query(),
		repo:  r,
	}
}

// QueryContext returns a type-safe query builder for TodoTag with context support.
// Use this when you need to control query timeouts, cancellation, or pass context values.
//
// Examples:
//
//	// With timeout context
//	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
//	defer cancel()
//	results, err := repo.QueryContext(ctx).Find()
//
//	// With cancellation
//	ctx, cancel := context.WithCancel(context.Background())
//	go func() { time.Sleep(time.Second); cancel() }()
//	results, err := repo.QueryContext(ctx).Find()
//
//	// Simple query with context
//	results, err := repo.QueryContext(ctx).Find()
func (r *TodoTagRepository) QueryContext(ctx context.Context) *TodoTagQuery {
	return &TodoTagQuery{
		Query: r.Repository.QueryContext(ctx),
		repo:  r,
	}
}

// TodoTagQuery provides type-safe query building for TodoTag
//
// Query Methods (returned by Query()):
//   - Where(condition) - Add WHERE conditions
//   - OrderBy(expressions...) - Add ORDER BY
//   - Limit(limit) - Set LIMIT
//   - Offset(offset) - Set OFFSET
//   - Join(type, table, condition) - Generic join
//   - InnerJoin(table, condition) - Inner join
//   - LeftJoin(table, condition) - Left join
//   - RightJoin(table, condition) - Right join
//   - FullJoin(table, condition) - Full outer join
//   - Include(relationships...) - Load relationships
//   - IncludeWhere(relationship, conditions...) - Load relationships with conditions
//   - WithTx(tx) - Execute within transaction
//
// Execution Methods:
//   - Find() - Execute query and return all records
//   - First() - Execute query and return first record
//   - Count() - Execute count query
//   - Exists() - Check if any records exist
//   - Delete() - Execute DELETE query
//   - ExecuteRaw(query, args...) - Execute raw SQL
//
// Example usage:
//
//	// Simple query
//	results, err := repo.Query().Where(TodoTags.FieldName.Eq("value")).Find()
//
//	// Complex query with joins and ordering
//	results, err := repo.Query().
//	    Where(condition).
//	    OrderBy("created_at DESC").
//	    Limit(10).
//	    Find()
//
//	// Query with relationships
//	results, err := repo.Query().
//	    Include("RelationshipName").
//	    Where(condition).
//	    Find()
type TodoTagQuery struct {
	*orm.Query[TodoTag]
	repo *TodoTagRepository
}

// Where applies a filtering condition to the query.
// Use the type-safe column references from TodoTags for conditions.
//
// Examples:
//
//	// Time-based queries
//	query.Where(TodoTags.CreatedAt.After(time.Now().AddDate(0, -1, 0)))
//	// Combine conditions
//	query.Where(TodoTags.TodoID.Eq("value").And(TodoTags.TagID.IsNotNull()))
func (q *TodoTagQuery) Where(condition orm.Condition) *TodoTagQuery {
	q.Query = q.Query.Where(condition)
	return q
}

// OrderBy specifies the order of results using column names or expressions.
// Use DESC suffix for descending order, ASC (or no suffix) for ascending.
//
// Examples:
//
//	// Order by time field (most recent first)
//	query.OrderBy("todo_id DESC")
//	// Multiple columns
//	query.OrderBy("todo_id DESC", "tag_id")
//	// Complex expressions
//	query.OrderBy("CASE WHEN active THEN 0 ELSE 1 END", "created_at DESC")
func (q *TodoTagQuery) OrderBy(expressions ...string) *TodoTagQuery {
	q.Query = q.Query.OrderBy(expressions...)
	return q
}

// Limit restricts the number of results returned.
// Useful for pagination and preventing large result sets.
//
// Examples:
//
//	// Get first 10 results
//	query.Limit(10)
//	// Get top 100 most recent todotags
//	query.OrderBy("created_at DESC").Limit(100)
func (q *TodoTagQuery) Limit(limit uint64) *TodoTagQuery {
	q.Query = q.Query.Limit(limit)
	return q
}

// Offset skips the specified number of results.
// Typically used with Limit for pagination.
//
// Examples:
//
//	// Skip first 20 results (page 3 with 10 per page)
//	query.Offset(20).Limit(10)
//	// Get results 51-100
//	query.Offset(50).Limit(50)
func (q *TodoTagQuery) Offset(offset uint64) *TodoTagQuery {
	q.Query = q.Query.Offset(offset)
	return q
}

// Find executes the query and returns all matching TodoTag records.
// Returns an empty slice if no records are found.
//
// Examples:
//
//	// Get all todotags
//	allTodoTags, err := repo.Query().Find()
func (q *TodoTagQuery) Find() ([]TodoTag, error) {
	return q.Query.Find()
}

// First executes the query and returns the first matching TodoTag record.
// Returns nil if no record is found. Use with OrderBy to get specific record.
//
// Examples:
//
//	// Get first todotag
//	firstTodoTag, err := repo.Query().First()
//	// Get most recent todotag
//	latestTodoTag, err := repo.Query().OrderBy("CreatedAt DESC").First()
func (q *TodoTagQuery) First() (*TodoTag, error) {
	return q.Query.First()
}

// Count returns the number of TodoTag records matching the query conditions.
// Does not load the actual records, making it efficient for large datasets.
//
// Examples:
//
//	// Count all todotags
//	total, err := repo.Query().Count()
func (q *TodoTagQuery) Count() (int64, error) {
	return q.Query.Count()
}

// Exists checks if any TodoTag records match the query conditions.
// Returns true if at least one record exists, false otherwise.
// More efficient than Count() when you only need to know if records exist.
//
// Examples:
//
//	// Check if any todotags exist
//	hasAny, err := repo.Query().Exists()
func (q *TodoTagQuery) Exists() (bool, error) {
	return q.Query.Exists()
}

// Delete removes all TodoTag records matching the query conditions.
// Returns the number of records deleted.
// WARNING: This is a bulk operation that cannot be undone.
//
// Examples:
//
//	// Delete all todotags (use with caution!)
//	deleted, err := repo.Query().Delete()
func (q *TodoTagQuery) Delete() (int64, error) {
	return q.Query.Delete()
}
