// Code generated by Storm ORM generator. DO NOT EDIT.
// Generated at: 2025-07-15 12:54:23

package todo

import (
	"github.com/eleven-am/storm/internal/orm"
	"time"
)

// TodoTagQuery provides type-safe query building for TodoTag
type TodoTagQuery struct {
	*orm.Query[TodoTag]
	repo *TodoTagRepository
}

// Where adds a type-safe WHERE condition
func (q *TodoTagQuery) Where(condition orm.Condition) *TodoTagQuery {
	q.Query = q.Query.Where(condition)
	return q
}

// OrderBy adds ordering to the query
func (q *TodoTagQuery) OrderBy(expressions ...string) *TodoTagQuery {
	q.Query = q.Query.OrderBy(expressions...)
	return q
}

// Limit sets the LIMIT clause
func (q *TodoTagQuery) Limit(limit uint64) *TodoTagQuery {
	q.Query = q.Query.Limit(limit)
	return q
}

// Offset sets the OFFSET clause
func (q *TodoTagQuery) Offset(offset uint64) *TodoTagQuery {
	q.Query = q.Query.Offset(offset)
	return q
}

// Type-safe column-specific query methods

// WhereTodoIDEq adds WHERE todo_id = condition
func (q *TodoTagQuery) WhereTodoIDEq(value string) *TodoTagQuery {
	return q.Where(TodoTags.TodoID.Eq(value))
}

// WhereTodoIDLike adds WHERE todo_id LIKE condition
func (q *TodoTagQuery) WhereTodoIDLike(pattern string) *TodoTagQuery {
	return q.Where(TodoTags.TodoID.Like(pattern))
}

// WhereTagIDEq adds WHERE tag_id = condition
func (q *TodoTagQuery) WhereTagIDEq(value string) *TodoTagQuery {
	return q.Where(TodoTags.TagID.Eq(value))
}

// WhereTagIDLike adds WHERE tag_id LIKE condition
func (q *TodoTagQuery) WhereTagIDLike(pattern string) *TodoTagQuery {
	return q.Where(TodoTags.TagID.Like(pattern))
}

// WhereCreatedAtEq adds WHERE created_at = condition
func (q *TodoTagQuery) WhereCreatedAtEq(value time.Time) *TodoTagQuery {
	return q.Where(TodoTags.CreatedAt.Eq(value))
}

// WhereCreatedAtAfter adds WHERE created_at > condition
func (q *TodoTagQuery) WhereCreatedAtAfter(value time.Time) *TodoTagQuery {
	return q.Where(TodoTags.CreatedAt.Gt(value))
}

// WhereCreatedAtBefore adds WHERE created_at < condition
func (q *TodoTagQuery) WhereCreatedAtBefore(value time.Time) *TodoTagQuery {
	return q.Where(TodoTags.CreatedAt.Lt(value))
}

// WhereCreatedAtBetween adds WHERE created_at BETWEEN condition
func (q *TodoTagQuery) WhereCreatedAtBetween(start, end time.Time) *TodoTagQuery {
	return q.Where(TodoTags.CreatedAt.Between(start, end))
}

// Ordering methods

// OrderByTodoIDAsc adds ORDER BY todo_id ASC
func (q *TodoTagQuery) OrderByTodoIDAsc() *TodoTagQuery {
	return q.OrderBy(TodoTags.TodoID.Asc())
}

// OrderByTodoIDDesc adds ORDER BY todo_id DESC
func (q *TodoTagQuery) OrderByTodoIDDesc() *TodoTagQuery {
	return q.OrderBy(TodoTags.TodoID.Desc())
}

// OrderByTagIDAsc adds ORDER BY tag_id ASC
func (q *TodoTagQuery) OrderByTagIDAsc() *TodoTagQuery {
	return q.OrderBy(TodoTags.TagID.Asc())
}

// OrderByTagIDDesc adds ORDER BY tag_id DESC
func (q *TodoTagQuery) OrderByTagIDDesc() *TodoTagQuery {
	return q.OrderBy(TodoTags.TagID.Desc())
}

// OrderByCreatedAtAsc adds ORDER BY created_at ASC
func (q *TodoTagQuery) OrderByCreatedAtAsc() *TodoTagQuery {
	return q.OrderBy(TodoTags.CreatedAt.Asc())
}

// OrderByCreatedAtDesc adds ORDER BY created_at DESC
func (q *TodoTagQuery) OrderByCreatedAtDesc() *TodoTagQuery {
	return q.OrderBy(TodoTags.CreatedAt.Desc())
}

// Execution methods return the underlying Query methods
func (q *TodoTagQuery) Find() ([]TodoTag, error) {
	return q.Query.Find()
}

func (q *TodoTagQuery) First() (*TodoTag, error) {
	return q.Query.First()
}

func (q *TodoTagQuery) Count() (int64, error) {
	return q.Query.Count()
}

func (q *TodoTagQuery) Exists() (bool, error) {
	return q.Query.Exists()
}

func (q *TodoTagQuery) Delete() (int64, error) {
	return q.Query.Delete()
}
