//go:build !exclude_generated
// +build !exclude_generated

// Code generated by storm orm generate-orm; DO NOT EDIT.
//
// This file was automatically generated from Go struct definitions.
// Any changes made to this file will be lost when regenerating.
//
// Source package: todo
// Model: Todo
// Generated on: 2025-07-17 00:36:07 CEST
//
// To regenerate this file, run:
//   storm orm generate-orm --package=todo
//
// For more information, see:
//   https://github.com/eleven-am/storm

package todo

import (
	"context"
	"fmt"
	"github.com/eleven-am/storm/internal/orm"
	"github.com/jmoiron/sqlx"
)

// TodoRepository provides type-safe operations for Todo
//
// The repository inherits these operations from orm.Repository:
//
// Single Record Operations:
//   - Create(ctx, record) - Insert single record
//   - FindByID(ctx, id) - Find record by primary key
//   - Update(ctx, record) - Update single record by primary key
//   - Delete(ctx, id) - Delete record by primary key ID
//   - DeleteRecord(ctx, record) - Delete record using the record instance
//
// Batch Operations:
//   - CreateMany(ctx, records) - Insert multiple records in transaction
//   - UpdateMany(ctx, updates, condition) - Update multiple records with condition
//   - BulkUpdate(ctx, records, opts) - Bulk update using CTE with VALUES
//   - Upsert(ctx, record, opts) - Insert or update on conflict
//   - UpsertMany(ctx, records, opts) - Batch upsert operations
//
// Query Building:
//   - Query() - Create new query builder for complex queries
//   - QueryContext(ctx) - Create query builder with context support
//
// Example usage:
//
//	// Single operations
//	todo, err := repo.FindByID(ctx, "123")
//	err = repo.Create(ctx, &newTodo)
//
//	// Batch operations
//	err = repo.CreateMany(ctx, multipleTodos)
//	rowsAffected, err := repo.UpdateMany(ctx, updates, condition)
//
//	// Complex queries
//	results, err := repo.Query().Where(condition).OrderBy("created_at DESC").Find()
type TodoRepository struct {
	*orm.Repository[Todo]
}

func newTodoRepository(db *sqlx.DB) (*TodoRepository, error) {
	baseRepo, err := orm.NewRepository[Todo](db, TodoMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository: %w", err)
	}

	return &TodoRepository{
		Repository: baseRepo,
	}, nil
}

func newTodoRepositoryWithTx(tx *sqlx.Tx) (*TodoRepository, error) {
	baseRepo, err := orm.NewRepositoryWithTx[Todo](tx, TodoMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository with transaction: %w", err)
	}

	return &TodoRepository{
		Repository: baseRepo,
	}, nil
}

// Query returns a type-safe query builder for Todo
//
// Example:
//
//	filteredTodos, err := repo.Query().
//	    Where(Todos.UserID.Like("%search%")).
//	    OrderBy(Todos.DueDate.Desc()).
func (r *TodoRepository) Query() *TodoQuery {
	return &TodoQuery{
		Query: r.Repository.Query(),
		repo:  r,
	}
}

// QueryContext returns a type-safe query builder for Todo with context support.
// Use this when you need to control query timeouts, cancellation, or pass context values.
//
// Examples:
//
//	// With timeout context
//	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
//	defer cancel()
//	results, err := repo.QueryContext(ctx).Find()
//
//	// With cancellation
//	ctx, cancel := context.WithCancel(context.Background())
//	go func() { time.Sleep(time.Second); cancel() }()
//	results, err := repo.QueryContext(ctx).Find()
//
//	// Complex query with context
//	results, err := repo.QueryContext(ctx).
//	    Where(Todos.UserID.Like("%search%")).
//	    Limit(100).Find()
func (r *TodoRepository) QueryContext(ctx context.Context) *TodoQuery {
	return &TodoQuery{
		Query: r.Repository.QueryContext(ctx),
		repo:  r,
	}
}

// WithUser includes the User relationship in queries
//
// Example:
//
//	todoWithOwner, err := repo.WithUser().Find()
//	// Each Todo will have its User loaded
func (r *TodoRepository) WithUser() *TodoQuery {
	return &TodoQuery{
		Query: r.Repository.Query().Include("User"),
		repo:  r,
	}
}

// WithCategory includes the Category relationship in queries
//
// Example:
//
//	todoWithOwner, err := repo.WithCategory().Find()
//	// Each Todo will have its Category loaded
func (r *TodoRepository) WithCategory() *TodoQuery {
	return &TodoQuery{
		Query: r.Repository.Query().Include("Category"),
		repo:  r,
	}
}

// WithTags includes the Tags relationship in queries
//
// Example:
//
//	todoWithTags, err := repo.WithTags().Find()
func (r *TodoRepository) WithTags() *TodoQuery {
	return &TodoQuery{
		Query: r.Repository.Query().Include("Tags"),
		repo:  r,
	}
}

// WithComments includes the Comments relationship in queries
//
// Example:
//
//	todoWithAllComments, err := repo.WithComments().Find()
//	// Each Todo will have its Comments slice populated
func (r *TodoRepository) WithComments() *TodoQuery {
	return &TodoQuery{
		Query: r.Repository.Query().Include("Comments"),
		repo:  r,
	}
}

// TodoQuery provides type-safe query building for Todo
//
// Query Methods (returned by Query()):
//   - Where(condition) - Add WHERE conditions
//   - OrderBy(expressions...) - Add ORDER BY
//   - Limit(limit) - Set LIMIT
//   - Offset(offset) - Set OFFSET
//   - Join(type, table, condition) - Generic join
//   - InnerJoin(table, condition) - Inner join
//   - LeftJoin(table, condition) - Left join
//   - RightJoin(table, condition) - Right join
//   - FullJoin(table, condition) - Full outer join
//   - Include(relationships...) - Load relationships
//   - IncludeWhere(relationship, conditions...) - Load relationships with conditions
//   - WithTx(tx) - Execute within transaction
//
// Execution Methods:
//   - Find() - Execute query and return all records
//   - First() - Execute query and return first record
//   - Count() - Execute count query
//   - Exists() - Check if any records exist
//   - Delete() - Execute DELETE query
//   - ExecuteRaw(query, args...) - Execute raw SQL
//
// Example usage:
//
//	// Simple query
//	results, err := repo.Query().Where(Todos.FieldName.Eq("value")).Find()
//
//	// Complex query with joins and ordering
//	results, err := repo.Query().
//	    Where(condition).
//	    OrderBy("created_at DESC").
//	    Limit(10).
//	    Find()
//
//	// Query with relationships
//	results, err := repo.Query().
//	    Include("RelationshipName").
//	    Where(condition).
//	    Find()
type TodoQuery struct {
	*orm.Query[Todo]
	repo *TodoRepository
}

// Where applies a filtering condition to the query.
// Use the type-safe column references from Todos for conditions.
//
// Examples:
//
//	// Exact match
//	query.Where(Todos.UserID.Eq("exact-value"))
//	// Pattern matching
//	query.Where(Todos.UserID.Like("%search%"))
//	// Multiple values
//	query.Where(Todos.UserID.In([]string{"value1", "value2"}))
//	// Time-based queries
//	query.Where(Todos.DueDate.After(time.Now().AddDate(0, -1, 0)))
//	// Combine conditions
//	query.Where(Todos.ID.Eq("value").And(Todos.UserID.IsNotNull()))
func (q *TodoQuery) Where(condition orm.Condition) *TodoQuery {
	q.Query = q.Query.Where(condition)
	return q
}

// OrderBy specifies the order of results using column names or expressions.
// Use DESC suffix for descending order, ASC (or no suffix) for ascending.
//
// Examples:
//
//	// Order by time field (most recent first)
//	query.OrderBy("id DESC")
//	// Order by string field alphabetically
//	query.OrderBy("id")
//	// Multiple columns
//	query.OrderBy("id DESC", "user_id")
//	// Complex expressions
//	query.OrderBy("CASE WHEN active THEN 0 ELSE 1 END", "created_at DESC")
func (q *TodoQuery) OrderBy(expressions ...string) *TodoQuery {
	q.Query = q.Query.OrderBy(expressions...)
	return q
}

// Limit restricts the number of results returned.
// Useful for pagination and preventing large result sets.
//
// Examples:
//
//	// Get first 10 results
//	query.Limit(10)
//	// Get top 100 most recent todos
//	query.OrderBy("created_at DESC").Limit(100)
func (q *TodoQuery) Limit(limit uint64) *TodoQuery {
	q.Query = q.Query.Limit(limit)
	return q
}

// Offset skips the specified number of results.
// Typically used with Limit for pagination.
//
// Examples:
//
//	// Skip first 20 results (page 3 with 10 per page)
//	query.Offset(20).Limit(10)
//	// Get results 51-100
//	query.Offset(50).Limit(50)
func (q *TodoQuery) Offset(offset uint64) *TodoQuery {
	q.Query = q.Query.Offset(offset)
	return q
}

// Find executes the query and returns all matching Todo records.
// Returns an empty slice if no records are found.
//
// Examples:
//
//	// Get all todos
//	allTodos, err := repo.Query().Find()
//	// Search todos by userid
//	matchingTodos, err := repo.Query().Where(Todos.UserID.Like("%search%")).Find()
func (q *TodoQuery) Find() ([]Todo, error) {
	return q.Query.Find()
}

// First executes the query and returns the first matching Todo record.
// Returns nil if no record is found. Use with OrderBy to get specific record.
//
// Examples:
//
//	// Get first todo
//	firstTodo, err := repo.Query().First()
//	// Get most recent todo
//	latestTodo, err := repo.Query().OrderBy("DueDate DESC").First()
//	// Get specific todo by userid
//	specificTodo, err := repo.Query().Where(Todos.UserID.Eq("value")).First()
func (q *TodoQuery) First() (*Todo, error) {
	return q.Query.First()
}

// Count returns the number of Todo records matching the query conditions.
// Does not load the actual records, making it efficient for large datasets.
//
// Examples:
//
//	// Count all todos
//	total, err := repo.Query().Count()
//	// Count todos matching criteria
//	matchingCount, err := repo.Query().Where(Todos.UserID.Like("%search%")).Count()
func (q *TodoQuery) Count() (int64, error) {
	return q.Query.Count()
}

// Exists checks if any Todo records match the query conditions.
// Returns true if at least one record exists, false otherwise.
// More efficient than Count() when you only need to know if records exist.
//
// Examples:
//
//	// Check if any todos exist
//	hasAny, err := repo.Query().Exists()
//	// Check if todo with specific userid exists
//	exists, err := repo.Query().Where(Todos.UserID.Eq("value")).Exists()
func (q *TodoQuery) Exists() (bool, error) {
	return q.Query.Exists()
}

// Delete removes all Todo records matching the query conditions.
// Returns the number of records deleted.
// WARNING: This is a bulk operation that cannot be undone.
//
// Examples:
//
//	// Delete all todos (use with caution!)
//	deleted, err := repo.Query().Delete()
//	// Delete todos matching criteria
//	deleted, err := repo.Query().Where(Todos.UserID.Like("temp_%")).Delete()
func (q *TodoQuery) Delete() (int64, error) {
	return q.Query.Delete()
}
