//go:build !exclude_generated
// +build !exclude_generated

// Code generated by storm orm generate-orm; DO NOT EDIT.
//
// This file was automatically generated from Go struct definitions.
// Any changes made to this file will be lost when regenerating.
//
// Source package: todo
// Model: TodoTag
// Generated on: 2025-07-17 01:02:48 CEST
//
// To regenerate this file, run:
//   storm orm generate-orm --package=todo
//
// For more information, see:
//   https://github.com/eleven-am/storm

package todo

import (
	"github.com/eleven-am/storm/internal/orm"
)

// TodoTagMetadata provides compile-time metadata for TodoTag
var TodoTagMetadata = &orm.ModelMetadata{
	TableName:  "todo_tags",
	StructName: "TodoTag",

	Columns: map[string]*orm.ColumnMetadata{
		"TodoID": {
			FieldName:       "TodoID",
			DBName:          "todo_id",
			GoType:          "string",
			IsPointer:       false,
			IsPrimaryKey:    true,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(TodoTag)
				return m.TodoID
			},
		},
		"TagID": {
			FieldName:       "TagID",
			DBName:          "tag_id",
			GoType:          "string",
			IsPointer:       false,
			IsPrimaryKey:    true,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(TodoTag)
				return m.TagID
			},
		},
		"CreatedAt": {
			FieldName:       "CreatedAt",
			DBName:          "created_at",
			GoType:          "time.Time",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: true,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(TodoTag)
				return m.CreatedAt
			},
		},
	},

	ColumnMap: map[string]string{
		"TodoID":    "todo_id",
		"TagID":     "tag_id",
		"CreatedAt": "created_at",
	},

	ReverseMap: map[string]string{
		"todo_id":    "TodoID",
		"tag_id":     "TagID",
		"created_at": "CreatedAt",
	},

	PrimaryKeys: []string{
		"todo_id",
		"tag_id",
	},

	Relationships: map[string]*orm.RelationshipMetadata{},
}
