//go:build !exclude_generated
// +build !exclude_generated

// Code generated by storm orm generate-orm; DO NOT EDIT.
//
// This file was automatically generated from Go struct definitions.
// Any changes made to this file will be lost when regenerating.
//
// Source package: models
// Model: DlqMessage
// Generated on: 2025-07-16 21:12:15 CEST
//
// To regenerate this file, run:
//   storm orm generate-orm --package=models
//
// For more information, see:
//   https://github.com/eleven-am/storm

package models

import (
	"context"
	"fmt"
	"github.com/eleven-am/storm/internal/orm"
	"github.com/jmoiron/sqlx"
)

// DlqMessageRepository provides type-safe operations for DlqMessage
// Inherits standard CRUD operations from orm.Repository:
// Find, FindAll, Create, Update, Delete, UpsertMany, BulkUpdate, etc.
type DlqMessageRepository struct {
	*orm.Repository[DlqMessage]
}

// newDlqMessageRepository creates a new DlqMessage repository (internal use only - use Storm)
func newDlqMessageRepository(db *sqlx.DB) (*DlqMessageRepository, error) {
	baseRepo, err := orm.NewRepository[DlqMessage](db, DlqMessageMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository: %w", err)
	}

	return &DlqMessageRepository{
		Repository: baseRepo,
	}, nil
}

// newDlqMessageRepositoryWithTx creates a new DlqMessage repository using an existing transaction (internal use only - use Storm)
func newDlqMessageRepositoryWithTx(tx *sqlx.Tx) (*DlqMessageRepository, error) {
	baseRepo, err := orm.NewRepositoryWithTx[DlqMessage](tx, DlqMessageMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository with transaction: %w", err)
	}

	return &DlqMessageRepository{
		Repository: baseRepo,
	}, nil
}

// Query returns a type-safe query builder for DlqMessage
//
// Example:
//
//	filteredDlqMessages, err := repo.Query().
//	    Where(DlqMessages.MessageId.Like("%search%")).
//	    OrderBy(DlqMessages.FirstFailure.Desc()).
//	    Limit(10).
//	    Find()
func (r *DlqMessageRepository) Query() *DlqMessageQuery {
	return &DlqMessageQuery{
		Query: r.Repository.Query(),
		repo:  r,
	}
}

// QueryContext returns a type-safe query builder for DlqMessage with context
//
// Example:
//
//	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
//	defer cancel()
//	results, err := repo.QueryContext(ctx).
//	    Limit(100).
//	    Find()
func (r *DlqMessageRepository) QueryContext(ctx context.Context) *DlqMessageQuery {
	return &DlqMessageQuery{
		Query: r.Repository.QueryContext(ctx),
		repo:  r,
	}
}

// WithPipeline includes the Pipeline relationship in queries
//
// Example:
//
//	dlqmessageWithOwner, err := repo.WithPipeline().Find()
//	// Each DlqMessage will have its Pipeline loaded
func (r *DlqMessageRepository) WithPipeline() *DlqMessageQuery {
	return &DlqMessageQuery{
		Query: r.Repository.Query().Include("Pipeline"),
		repo:  r,
	}
}

// WithTrigger includes the Trigger relationship in queries
//
// Example:
//
//	dlqmessageWithOwner, err := repo.WithTrigger().Find()
//	// Each DlqMessage will have its Trigger loaded
func (r *DlqMessageRepository) WithTrigger() *DlqMessageQuery {
	return &DlqMessageQuery{
		Query: r.Repository.Query().Include("Trigger"),
		repo:  r,
	}
}

// DlqMessageQuery provides type-safe query building for DlqMessage
type DlqMessageQuery struct {
	*orm.Query[DlqMessage]
	repo *DlqMessageRepository
}

// Where adds a type-safe WHERE condition
func (q *DlqMessageQuery) Where(condition orm.Condition) *DlqMessageQuery {
	q.Query = q.Query.Where(condition)
	return q
}

// OrderBy adds ordering to the query
func (q *DlqMessageQuery) OrderBy(expressions ...string) *DlqMessageQuery {
	q.Query = q.Query.OrderBy(expressions...)
	return q
}

// Limit sets the LIMIT clause
func (q *DlqMessageQuery) Limit(limit uint64) *DlqMessageQuery {
	q.Query = q.Query.Limit(limit)
	return q
}

// Offset sets the OFFSET clause
func (q *DlqMessageQuery) Offset(offset uint64) *DlqMessageQuery {
	q.Query = q.Query.Offset(offset)
	return q
}

// Find executes the query and returns all matching records
func (q *DlqMessageQuery) Find() ([]DlqMessage, error) {
	return q.Query.Find()
}

// First executes the query and returns the first matching record
func (q *DlqMessageQuery) First() (*DlqMessage, error) {
	return q.Query.First()
}

// Count executes the query and returns the count of matching records
func (q *DlqMessageQuery) Count() (int64, error) {
	return q.Query.Count()
}

// Exists executes the query and returns true if any records match
func (q *DlqMessageQuery) Exists() (bool, error) {
	return q.Query.Exists()
}

// Delete executes the query and deletes all matching records
func (q *DlqMessageQuery) Delete() (int64, error) {
	return q.Query.Delete()
}
