//go:build !exclude_generated
// +build !exclude_generated

// Code generated by storm orm generate-orm; DO NOT EDIT.
//
// This file was automatically generated from Go struct definitions.
// Any changes made to this file will be lost when regenerating.
//
// Source package: models
// Model: ExecutionLog
// Generated on: 2025-07-16 21:12:15 CEST
//
// To regenerate this file, run:
//   storm orm generate-orm --package=models
//
// For more information, see:
//   https://github.com/eleven-am/storm

package models

import (
	"context"
	"fmt"
	"github.com/eleven-am/storm/internal/orm"
	"github.com/jmoiron/sqlx"
)

// ExecutionLogRepository provides type-safe operations for ExecutionLog
// Inherits standard CRUD operations from orm.Repository:
// Find, FindAll, Create, Update, Delete, UpsertMany, BulkUpdate, etc.
type ExecutionLogRepository struct {
	*orm.Repository[ExecutionLog]
}

// newExecutionLogRepository creates a new ExecutionLog repository (internal use only - use Storm)
func newExecutionLogRepository(db *sqlx.DB) (*ExecutionLogRepository, error) {
	baseRepo, err := orm.NewRepository[ExecutionLog](db, ExecutionLogMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository: %w", err)
	}

	return &ExecutionLogRepository{
		Repository: baseRepo,
	}, nil
}

// newExecutionLogRepositoryWithTx creates a new ExecutionLog repository using an existing transaction (internal use only - use Storm)
func newExecutionLogRepositoryWithTx(tx *sqlx.Tx) (*ExecutionLogRepository, error) {
	baseRepo, err := orm.NewRepositoryWithTx[ExecutionLog](tx, ExecutionLogMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository with transaction: %w", err)
	}

	return &ExecutionLogRepository{
		Repository: baseRepo,
	}, nil
}

// Query returns a type-safe query builder for ExecutionLog
//
// Example:
//
//	filteredExecutionLogs, err := repo.Query().
//	    Where(ExecutionLogs.ProjectId.Like("%search%")).
//	    OrderBy(ExecutionLogs.Id.Desc()).
//	    Limit(10).
//	    Find()
func (r *ExecutionLogRepository) Query() *ExecutionLogQuery {
	return &ExecutionLogQuery{
		Query: r.Repository.Query(),
		repo:  r,
	}
}

// QueryContext returns a type-safe query builder for ExecutionLog with context
//
// Example:
//
//	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
//	defer cancel()
//	results, err := repo.QueryContext(ctx).
//	    Limit(100).
//	    Find()
func (r *ExecutionLogRepository) QueryContext(ctx context.Context) *ExecutionLogQuery {
	return &ExecutionLogQuery{
		Query: r.Repository.QueryContext(ctx),
		repo:  r,
	}
}

// WithPipeline includes the Pipeline relationship in queries
//
// Example:
//
//	executionlogWithOwner, err := repo.WithPipeline().Find()
//	// Each ExecutionLog will have its Pipeline loaded
func (r *ExecutionLogRepository) WithPipeline() *ExecutionLogQuery {
	return &ExecutionLogQuery{
		Query: r.Repository.Query().Include("Pipeline"),
		repo:  r,
	}
}

// WithProject includes the Project relationship in queries
//
// Example:
//
//	executionlogWithOwner, err := repo.WithProject().Find()
//	// Each ExecutionLog will have its Project loaded
func (r *ExecutionLogRepository) WithProject() *ExecutionLogQuery {
	return &ExecutionLogQuery{
		Query: r.Repository.Query().Include("Project"),
		repo:  r,
	}
}

// WithTrigger includes the Trigger relationship in queries
//
// Example:
//
//	executionlogWithOwner, err := repo.WithTrigger().Find()
//	// Each ExecutionLog will have its Trigger loaded
func (r *ExecutionLogRepository) WithTrigger() *ExecutionLogQuery {
	return &ExecutionLogQuery{
		Query: r.Repository.Query().Include("Trigger"),
		repo:  r,
	}
}

// ExecutionLogQuery provides type-safe query building for ExecutionLog
type ExecutionLogQuery struct {
	*orm.Query[ExecutionLog]
	repo *ExecutionLogRepository
}

// Where adds a type-safe WHERE condition
func (q *ExecutionLogQuery) Where(condition orm.Condition) *ExecutionLogQuery {
	q.Query = q.Query.Where(condition)
	return q
}

// OrderBy adds ordering to the query
func (q *ExecutionLogQuery) OrderBy(expressions ...string) *ExecutionLogQuery {
	q.Query = q.Query.OrderBy(expressions...)
	return q
}

// Limit sets the LIMIT clause
func (q *ExecutionLogQuery) Limit(limit uint64) *ExecutionLogQuery {
	q.Query = q.Query.Limit(limit)
	return q
}

// Offset sets the OFFSET clause
func (q *ExecutionLogQuery) Offset(offset uint64) *ExecutionLogQuery {
	q.Query = q.Query.Offset(offset)
	return q
}

// Find executes the query and returns all matching records
func (q *ExecutionLogQuery) Find() ([]ExecutionLog, error) {
	return q.Query.Find()
}

// First executes the query and returns the first matching record
func (q *ExecutionLogQuery) First() (*ExecutionLog, error) {
	return q.Query.First()
}

// Count executes the query and returns the count of matching records
func (q *ExecutionLogQuery) Count() (int64, error) {
	return q.Query.Count()
}

// Exists executes the query and returns true if any records match
func (q *ExecutionLogQuery) Exists() (bool, error) {
	return q.Query.Exists()
}

// Delete executes the query and deletes all matching records
func (q *ExecutionLogQuery) Delete() (int64, error) {
	return q.Query.Delete()
}
