//go:build !exclude_generated
// +build !exclude_generated

// Code generated by storm orm generate-orm; DO NOT EDIT.
//
// This file was automatically generated from Go struct definitions.
// Any changes made to this file will be lost when regenerating.
//
// Source package: models
// Model: OauthToken
// Generated on: 2025-07-16 21:12:15 CEST
//
// To regenerate this file, run:
//   storm orm generate-orm --package=models
//
// For more information, see:
//   https://github.com/eleven-am/storm

package models

import (
	"context"
	"fmt"
	"github.com/eleven-am/storm/internal/orm"
	"github.com/jmoiron/sqlx"
)

// OauthTokenRepository provides type-safe operations for OauthToken
// Inherits standard CRUD operations from orm.Repository:
// Find, FindAll, Create, Update, Delete, UpsertMany, BulkUpdate, etc.
type OauthTokenRepository struct {
	*orm.Repository[OauthToken]
}

// newOauthTokenRepository creates a new OauthToken repository (internal use only - use Storm)
func newOauthTokenRepository(db *sqlx.DB) (*OauthTokenRepository, error) {
	baseRepo, err := orm.NewRepository[OauthToken](db, OauthTokenMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository: %w", err)
	}

	return &OauthTokenRepository{
		Repository: baseRepo,
	}, nil
}

// newOauthTokenRepositoryWithTx creates a new OauthToken repository using an existing transaction (internal use only - use Storm)
func newOauthTokenRepositoryWithTx(tx *sqlx.Tx) (*OauthTokenRepository, error) {
	baseRepo, err := orm.NewRepositoryWithTx[OauthToken](tx, OauthTokenMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository with transaction: %w", err)
	}

	return &OauthTokenRepository{
		Repository: baseRepo,
	}, nil
}

// Query returns a type-safe query builder for OauthToken
//
// Example:
//
//	filteredOauthTokens, err := repo.Query().
//	    Where(OauthTokens.ProjectId.Like("%search%")).
//	    OrderBy(OauthTokens.Id.Desc()).
//	    Limit(10).
//	    Find()
func (r *OauthTokenRepository) Query() *OauthTokenQuery {
	return &OauthTokenQuery{
		Query: r.Repository.Query(),
		repo:  r,
	}
}

// QueryContext returns a type-safe query builder for OauthToken with context
//
// Example:
//
//	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
//	defer cancel()
//	results, err := repo.QueryContext(ctx).
//	    Limit(100).
//	    Find()
func (r *OauthTokenRepository) QueryContext(ctx context.Context) *OauthTokenQuery {
	return &OauthTokenQuery{
		Query: r.Repository.QueryContext(ctx),
		repo:  r,
	}
}

// WithProject includes the Project relationship in queries
//
// Example:
//
//	oauthtokenWithOwner, err := repo.WithProject().Find()
//	// Each OauthToken will have its Project loaded
func (r *OauthTokenRepository) WithProject() *OauthTokenQuery {
	return &OauthTokenQuery{
		Query: r.Repository.Query().Include("Project"),
		repo:  r,
	}
}

// OauthTokenQuery provides type-safe query building for OauthToken
type OauthTokenQuery struct {
	*orm.Query[OauthToken]
	repo *OauthTokenRepository
}

// Where adds a type-safe WHERE condition
func (q *OauthTokenQuery) Where(condition orm.Condition) *OauthTokenQuery {
	q.Query = q.Query.Where(condition)
	return q
}

// OrderBy adds ordering to the query
func (q *OauthTokenQuery) OrderBy(expressions ...string) *OauthTokenQuery {
	q.Query = q.Query.OrderBy(expressions...)
	return q
}

// Limit sets the LIMIT clause
func (q *OauthTokenQuery) Limit(limit uint64) *OauthTokenQuery {
	q.Query = q.Query.Limit(limit)
	return q
}

// Offset sets the OFFSET clause
func (q *OauthTokenQuery) Offset(offset uint64) *OauthTokenQuery {
	q.Query = q.Query.Offset(offset)
	return q
}

// Find executes the query and returns all matching records
func (q *OauthTokenQuery) Find() ([]OauthToken, error) {
	return q.Query.Find()
}

// First executes the query and returns the first matching record
func (q *OauthTokenQuery) First() (*OauthToken, error) {
	return q.Query.First()
}

// Count executes the query and returns the count of matching records
func (q *OauthTokenQuery) Count() (int64, error) {
	return q.Query.Count()
}

// Exists executes the query and returns true if any records match
func (q *OauthTokenQuery) Exists() (bool, error) {
	return q.Query.Exists()
}

// Delete executes the query and deletes all matching records
func (q *OauthTokenQuery) Delete() (int64, error) {
	return q.Query.Delete()
}
