//go:build !exclude_generated
// +build !exclude_generated

// Code generated by storm orm generate-orm; DO NOT EDIT.
//
// This file was automatically generated from Go struct definitions.
// Any changes made to this file will be lost when regenerating.
//
// Source package: models
// Model: Project
// Generated on: 2025-07-16 21:12:15 CEST
//
// To regenerate this file, run:
//   storm orm generate-orm --package=models
//
// For more information, see:
//   https://github.com/eleven-am/storm

package models

import (
	"github.com/eleven-am/storm/internal/orm"
)

// ProjectMetadata provides compile-time metadata for Project
var ProjectMetadata = &orm.ModelMetadata{
	TableName:  "projects",
	StructName: "Project",

	Columns: map[string]*orm.ColumnMetadata{
		"Id": {
			FieldName:       "Id",
			DBName:          "id",
			GoType:          "string",
			IsPointer:       false,
			IsPrimaryKey:    true,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Project)
				return m.Id
			},
		},
		"TeamId": {
			FieldName:       "TeamId",
			DBName:          "team_id",
			GoType:          "string",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Project)
				return m.TeamId
			},
		},
		"Name": {
			FieldName:       "Name",
			DBName:          "name",
			GoType:          "string",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Project)
				return m.Name
			},
		},
		"CreatedAt": {
			FieldName:       "CreatedAt",
			DBName:          "created_at",
			GoType:          "time.Time",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: true,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Project)
				return m.CreatedAt
			},
		},
		"UpdatedAt": {
			FieldName:       "UpdatedAt",
			DBName:          "updated_at",
			GoType:          "time.Time",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: true,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Project)
				return m.UpdatedAt
			},
		},
	},

	ColumnMap: map[string]string{
		"Id":        "id",
		"TeamId":    "team_id",
		"Name":      "name",
		"CreatedAt": "created_at",
		"UpdatedAt": "updated_at",
	},

	ReverseMap: map[string]string{
		"id":         "Id",
		"team_id":    "TeamId",
		"name":       "Name",
		"created_at": "CreatedAt",
		"updated_at": "UpdatedAt",
	},

	PrimaryKeys: []string{
		"id",
	},

	Relationships: map[string]*orm.RelationshipMetadata{
		"Team": {
			Name:       "Team",
			Type:       "belongs_to",
			Target:     "Team",
			ForeignKey: "team_id",
			TargetKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*Project).Team = value.(*Team)
			},
			IsSlice: false,
		},
		"Triggers": {
			Name:       "Triggers",
			Type:       "has_many",
			Target:     "Trigger",
			ForeignKey: "project_id",
			SourceKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*Project).Triggers = value.([]Trigger)
			},
			IsSlice: true,
		},
		"AuthCredentials": {
			Name:       "AuthCredentials",
			Type:       "has_many",
			Target:     "AuthCredential",
			ForeignKey: "project_id",
			SourceKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*Project).AuthCredentials = value.([]AuthCredential)
			},
			IsSlice: true,
		},
		"Brokers": {
			Name:       "Brokers",
			Type:       "has_many",
			Target:     "Broker",
			ForeignKey: "project_id",
			SourceKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*Project).Brokers = value.([]Broker)
			},
			IsSlice: true,
		},
		"Pipelines": {
			Name:       "Pipelines",
			Type:       "has_many",
			Target:     "Pipeline",
			ForeignKey: "project_id",
			SourceKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*Project).Pipelines = value.([]Pipeline)
			},
			IsSlice: true,
		},
		"OauthTokens": {
			Name:       "OauthTokens",
			Type:       "has_many",
			Target:     "OauthToken",
			ForeignKey: "project_id",
			SourceKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*Project).OauthTokens = value.([]OauthToken)
			},
			IsSlice: true,
		},
		"PipelineEvents": {
			Name:       "PipelineEvents",
			Type:       "has_many",
			Target:     "PipelineEvent",
			ForeignKey: "project_id",
			SourceKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*Project).PipelineEvents = value.([]PipelineEvent)
			},
			IsSlice: true,
		},
		"ExecutionLogs": {
			Name:       "ExecutionLogs",
			Type:       "has_many",
			Target:     "ExecutionLog",
			ForeignKey: "project_id",
			SourceKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*Project).ExecutionLogs = value.([]ExecutionLog)
			},
			IsSlice: true,
		},
		"ApiKeys": {
			Name:       "ApiKeys",
			Type:       "has_many",
			Target:     "ApiKey",
			ForeignKey: "project_id",
			SourceKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*Project).ApiKeys = value.([]ApiKey)
			},
			IsSlice: true,
		},
	},
}
