//go:build !exclude_generated
// +build !exclude_generated

// Code generated by storm orm generate-orm; DO NOT EDIT.
//
// This file was automatically generated from Go struct definitions.
// Any changes made to this file will be lost when regenerating.
//
// Source package: models
// Model: Subscription
// Generated on: 2025-07-16 21:12:15 CEST
//
// To regenerate this file, run:
//   storm orm generate-orm --package=models
//
// For more information, see:
//   https://github.com/eleven-am/storm

package models

import (
	"context"
	"fmt"
	"github.com/eleven-am/storm/internal/orm"
	"github.com/jmoiron/sqlx"
)

// SubscriptionRepository provides type-safe operations for Subscription
// Inherits standard CRUD operations from orm.Repository:
// Find, FindAll, Create, Update, Delete, UpsertMany, BulkUpdate, etc.
type SubscriptionRepository struct {
	*orm.Repository[Subscription]
}

// newSubscriptionRepository creates a new Subscription repository (internal use only - use Storm)
func newSubscriptionRepository(db *sqlx.DB) (*SubscriptionRepository, error) {
	baseRepo, err := orm.NewRepository[Subscription](db, SubscriptionMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository: %w", err)
	}

	return &SubscriptionRepository{
		Repository: baseRepo,
	}, nil
}

// newSubscriptionRepositoryWithTx creates a new Subscription repository using an existing transaction (internal use only - use Storm)
func newSubscriptionRepositoryWithTx(tx *sqlx.Tx) (*SubscriptionRepository, error) {
	baseRepo, err := orm.NewRepositoryWithTx[Subscription](tx, SubscriptionMetadata)
	if err != nil {
		return nil, fmt.Errorf("failed to create base repository with transaction: %w", err)
	}

	return &SubscriptionRepository{
		Repository: baseRepo,
	}, nil
}

// Query returns a type-safe query builder for Subscription
//
// Example:
//
//	activeSubscriptions, err := repo.Query().
//	    Where(Subscriptions.Active.Eq(true)).
//	    OrderBy(Subscriptions.Id.Desc()).
//	    Limit(10).
//	    Find()
func (r *SubscriptionRepository) Query() *SubscriptionQuery {
	return &SubscriptionQuery{
		Query: r.Repository.Query(),
		repo:  r,
	}
}

// QueryContext returns a type-safe query builder for Subscription with context
//
// Example:
//
//	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
//	defer cancel()
//	results, err := repo.QueryContext(ctx).
//	    Limit(100).
//	    Find()
func (r *SubscriptionRepository) QueryContext(ctx context.Context) *SubscriptionQuery {
	return &SubscriptionQuery{
		Query: r.Repository.QueryContext(ctx),
		repo:  r,
	}
}

// WithPlan includes the Plan relationship in queries
//
// Example:
//
//	subscriptionWithOwner, err := repo.WithPlan().Find()
//	// Each Subscription will have its Plan loaded
func (r *SubscriptionRepository) WithPlan() *SubscriptionQuery {
	return &SubscriptionQuery{
		Query: r.Repository.Query().Include("Plan"),
		repo:  r,
	}
}

// WithTeam includes the Team relationship in queries
//
// Example:
//
//	subscriptionWithOwner, err := repo.WithTeam().Find()
//	// Each Subscription will have its Team loaded
func (r *SubscriptionRepository) WithTeam() *SubscriptionQuery {
	return &SubscriptionQuery{
		Query: r.Repository.Query().Include("Team"),
		repo:  r,
	}
}

// SubscriptionQuery provides type-safe query building for Subscription
type SubscriptionQuery struct {
	*orm.Query[Subscription]
	repo *SubscriptionRepository
}

// Where adds a type-safe WHERE condition
func (q *SubscriptionQuery) Where(condition orm.Condition) *SubscriptionQuery {
	q.Query = q.Query.Where(condition)
	return q
}

// OrderBy adds ordering to the query
func (q *SubscriptionQuery) OrderBy(expressions ...string) *SubscriptionQuery {
	q.Query = q.Query.OrderBy(expressions...)
	return q
}

// Limit sets the LIMIT clause
func (q *SubscriptionQuery) Limit(limit uint64) *SubscriptionQuery {
	q.Query = q.Query.Limit(limit)
	return q
}

// Offset sets the OFFSET clause
func (q *SubscriptionQuery) Offset(offset uint64) *SubscriptionQuery {
	q.Query = q.Query.Offset(offset)
	return q
}

// Find executes the query and returns all matching records
func (q *SubscriptionQuery) Find() ([]Subscription, error) {
	return q.Query.Find()
}

// First executes the query and returns the first matching record
func (q *SubscriptionQuery) First() (*Subscription, error) {
	return q.Query.First()
}

// Count executes the query and returns the count of matching records
func (q *SubscriptionQuery) Count() (int64, error) {
	return q.Query.Count()
}

// Exists executes the query and returns true if any records match
func (q *SubscriptionQuery) Exists() (bool, error) {
	return q.Query.Exists()
}

// Delete executes the query and deletes all matching records
func (q *SubscriptionQuery) Delete() (int64, error) {
	return q.Query.Delete()
}
