//go:build !exclude_generated
// +build !exclude_generated

// Code generated by storm orm generate-orm; DO NOT EDIT.
//
// This file was automatically generated from Go struct definitions.
// Any changes made to this file will be lost when regenerating.
//
// Source package: models
// Model: Subscription
// Generated on: 2025-07-16 21:12:15 CEST
//
// To regenerate this file, run:
//   storm orm generate-orm --package=models
//
// For more information, see:
//   https://github.com/eleven-am/storm

package models

import (
	"github.com/eleven-am/storm/internal/orm"
)

// SubscriptionMetadata provides compile-time metadata for Subscription
var SubscriptionMetadata = &orm.ModelMetadata{
	TableName:  "subscriptions",
	StructName: "Subscription",

	Columns: map[string]*orm.ColumnMetadata{
		"Id": {
			FieldName:       "Id",
			DBName:          "id",
			GoType:          "string",
			IsPointer:       false,
			IsPrimaryKey:    true,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Subscription)
				return m.Id
			},
		},
		"PlanId": {
			FieldName:       "PlanId",
			DBName:          "plan_id",
			GoType:          "string",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Subscription)
				return m.PlanId
			},
		},
		"TeamId": {
			FieldName:       "TeamId",
			DBName:          "team_id",
			GoType:          "string",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Subscription)
				return m.TeamId
			},
		},
		"Active": {
			FieldName:       "Active",
			DBName:          "active",
			GoType:          "bool",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Subscription)
				return m.Active
			},
		},
		"ExpiresAt": {
			FieldName:       "ExpiresAt",
			DBName:          "expires_at",
			GoType:          "time.Time",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Subscription)
				return m.ExpiresAt
			},
		},
		"CreatedAt": {
			FieldName:       "CreatedAt",
			DBName:          "created_at",
			GoType:          "time.Time",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: true,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Subscription)
				return m.CreatedAt
			},
		},
		"UpdatedAt": {
			FieldName:       "UpdatedAt",
			DBName:          "updated_at",
			GoType:          "time.Time",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: true,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(Subscription)
				return m.UpdatedAt
			},
		},
	},

	ColumnMap: map[string]string{
		"Id":        "id",
		"PlanId":    "plan_id",
		"TeamId":    "team_id",
		"Active":    "active",
		"ExpiresAt": "expires_at",
		"CreatedAt": "created_at",
		"UpdatedAt": "updated_at",
	},

	ReverseMap: map[string]string{
		"id":         "Id",
		"plan_id":    "PlanId",
		"team_id":    "TeamId",
		"active":     "Active",
		"expires_at": "ExpiresAt",
		"created_at": "CreatedAt",
		"updated_at": "UpdatedAt",
	},

	PrimaryKeys: []string{
		"id",
	},

	Relationships: map[string]*orm.RelationshipMetadata{
		"Plan": {
			Name:       "Plan",
			Type:       "belongs_to",
			Target:     "Plan",
			ForeignKey: "plan_id",
			TargetKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*Subscription).Plan = value.(*Plan)
			},
			IsSlice: false,
		},
		"Team": {
			Name:       "Team",
			Type:       "belongs_to",
			Target:     "Team",
			ForeignKey: "team_id",
			TargetKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*Subscription).Team = value.(*Team)
			},
			IsSlice: false,
		},
	},
}
