//go:build !exclude_generated
// +build !exclude_generated

// Code generated by storm orm generate-orm; DO NOT EDIT.
//
// This file was automatically generated from Go struct definitions.
// Any changes made to this file will be lost when regenerating.
//
// Source package: models
// Model: User
// Generated on: 2025-07-16 21:12:15 CEST
//
// To regenerate this file, run:
//   storm orm generate-orm --package=models
//
// For more information, see:
//   https://github.com/eleven-am/storm

package models

import (
	"github.com/eleven-am/storm/internal/orm"
)

// UserMetadata provides compile-time metadata for User
var UserMetadata = &orm.ModelMetadata{
	TableName:  "users",
	StructName: "User",

	Columns: map[string]*orm.ColumnMetadata{
		"Id": {
			FieldName:       "Id",
			DBName:          "id",
			GoType:          "string",
			IsPointer:       false,
			IsPrimaryKey:    true,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(User)
				return m.Id
			},
		},
		"TeamId": {
			FieldName:       "TeamId",
			DBName:          "team_id",
			GoType:          "string",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(User)
				return m.TeamId
			},
		},
		"Email": {
			FieldName:       "Email",
			DBName:          "email",
			GoType:          "string",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: false,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(User)
				return m.Email
			},
		},
		"CreatedAt": {
			FieldName:       "CreatedAt",
			DBName:          "created_at",
			GoType:          "time.Time",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: true,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(User)
				return m.CreatedAt
			},
		},
		"UpdatedAt": {
			FieldName:       "UpdatedAt",
			DBName:          "updated_at",
			GoType:          "time.Time",
			IsPointer:       false,
			IsPrimaryKey:    false,
			IsAutoGenerated: true,

			// Generated accessor functions for zero-reflection field access
			GetValue: func(model interface{}) interface{} {
				m := model.(User)
				return m.UpdatedAt
			},
		},
	},

	ColumnMap: map[string]string{
		"Id":        "id",
		"TeamId":    "team_id",
		"Email":     "email",
		"CreatedAt": "created_at",
		"UpdatedAt": "updated_at",
	},

	ReverseMap: map[string]string{
		"id":         "Id",
		"team_id":    "TeamId",
		"email":      "Email",
		"created_at": "CreatedAt",
		"updated_at": "UpdatedAt",
	},

	PrimaryKeys: []string{
		"id",
	},

	Relationships: map[string]*orm.RelationshipMetadata{
		"Team": {
			Name:       "Team",
			Type:       "belongs_to",
			Target:     "Team",
			ForeignKey: "team_id",
			TargetKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*User).Team = value.(*Team)
			},
			IsSlice: false,
		},
		"AuditLogs": {
			Name:       "AuditLogs",
			Type:       "has_many",
			Target:     "AuditLog",
			ForeignKey: "user_id",
			SourceKey:  "id",

			// Generated accessor functions for relationships
			SetValue: func(model interface{}, value interface{}) {
				model.(*User).AuditLogs = value.([]AuditLog)
			},
			IsSlice: true,
		},
	},
}
